const TABLE_MASTERY_TOLERANCE_MS = 5_000

function isLegacyTableMasteryFact(fact, completions) {
  if (String(fact?.operation || '') !== 'multiplication') return false
  const table = Number(fact?.level)
  if (!Number.isInteger(table) || table < 2 || table > 12) return false

  const window = fact?.window || {}
  if (Number(window.attempts) !== 1 || Number(window.correct) !== 1 || Number(window.rate) !== 1) {
    return false
  }

  const achievedAt = Number(fact?.achievedAt)
  if (!Number.isFinite(achievedAt)) return false

  return completions.some(completion =>
    Number(completion?.table) === table
    && Math.abs(Number(completion?.timestamp) - achievedAt) <= TABLE_MASTERY_TOLERANCE_MS
  )
}

/**
 * Revokes only legacy mastery facts that are provably generated by the old
 * table-drill completion side effect. Ordinary multiplication mastery is kept.
 */
export function repairLegacyTableMasteryFacts(profile) {
  const facts = Array.isArray(profile?.masteryFacts?.facts) ? profile.masteryFacts.facts : []
  const completions = Array.isArray(profile?.tableDrill?.completions)
    ? profile.tableDrill.completions
    : []
  if (facts.length === 0 || completions.length === 0) return 0

  if (!Array.isArray(profile.masteryFacts.revokedIds)) {
    profile.masteryFacts.revokedIds = []
  }
  const revoked = new Set(profile.masteryFacts.revokedIds)
  let repaired = 0

  for (const fact of facts) {
    if (!fact?.id || revoked.has(fact.id)) continue
    if (!isLegacyTableMasteryFact(fact, completions)) continue
    revoked.add(fact.id)
    repaired += 1
  }

  if (repaired > 0) {
    profile.masteryFacts.revokedIds = Array.from(revoked)
  }
  return repaired
}

