export function buildTicketSectionPanelProps({
  ticketQuestionInput,
  ticketAnswerInput,
  ticketTagsInput,
  ticketKindInput,
  ticketCsvInput,
  ticketTemplateFilter,
  ticketTagFilter,
  ticketSortBy,
  ticketTagOptions,
  ticketTemplateRows,
  setTicketQuestionInput,
  setTicketAnswerInput,
  setTicketTagsInput,
  setTicketKindInput,
  handleCreateTicketTemplate,
  setTicketCsvInput,
  handleImportTicketCsv,
  setTicketTemplateFilter,
  setTicketTagFilter,
  setTicketSortBy,
  handleCreateTicketDispatch,
  handleDeleteTicketTemplate,
  selectedTicketDispatchId,
  ticketDispatches,
  ticketDispatchImmediateFeedback,
  selectedClassIds,
  filteredStudents,
  classFilterOptions,
  ticketTargetClassSet,
  ticketStudentSearch,
  ticketFilteredStudentOptions,
  ticketTargetStudentSet,
  ticketResolvedTargetStudentIds,
  ticketHasExplicitTargets,
  ticketTargetClassIds,
  ticketTargetStudentIds,
  copiedTicketDispatchId,
  setSelectedTicketDispatchId,
  setTicketDispatchImmediateFeedback,
  handleTicketTargetsFromClassFilter,
  handleClearTicketTargets,
  handleToggleTicketTargetClass,
  setTicketStudentSearch,
  handleToggleTicketTargetStudent,
  handleCopyTicketLink,
  handlePublishTicketToHome,
  handleToggleTicketReveal,
  handleClearTicketFromHome,
  handleDeleteTicketDispatch,
  ticketSelectedDispatch,
  ticketResponseMeta,
  ticketResponseRows,
  onOpenStudentDetail,
  formatTimeAgo,
  ticketHistoryStudentId,
  ticketHistoryStudentOptions,
  ticketHistoryKindFilter,
  ticketHistoryResultFilter,
  ticketHistorySearch,
  ticketHistoryStudent,
  ticketHistorySummary,
  ticketHistoryRows,
  setTicketHistoryStudentId,
  setTicketHistoryKindFilter,
  setTicketHistoryResultFilter,
  setTicketHistorySearch
}) {
  const templatePanelProps = {
    ticketQuestionInput,
    ticketAnswerInput,
    ticketTagsInput,
    ticketKindInput,
    ticketCsvInput,
    ticketTemplateFilter,
    ticketTagFilter,
    ticketSortBy,
    ticketTagOptions,
    ticketTemplateRows,
    onSetTicketQuestionInput: setTicketQuestionInput,
    onSetTicketAnswerInput: setTicketAnswerInput,
    onSetTicketTagsInput: setTicketTagsInput,
    onSetTicketKindInput: setTicketKindInput,
    onCreateTicketTemplate: handleCreateTicketTemplate,
    onSetTicketCsvInput: setTicketCsvInput,
    onImportTicketCsv: handleImportTicketCsv,
    onSetTicketTemplateFilter: setTicketTemplateFilter,
    onSetTicketTagFilter: setTicketTagFilter,
    onSetTicketSortBy: setTicketSortBy,
    onCreateTicketDispatch: handleCreateTicketDispatch,
    onDeleteTicketTemplate: handleDeleteTicketTemplate
  }

  const dispatchPanelProps = {
    selectedTicketDispatchId,
    ticketDispatches,
    ticketDispatchImmediateFeedback,
    selectedClassIds,
    filteredStudentsCount: filteredStudents.length,
    classFilterOptions,
    ticketTargetClassSet,
    ticketStudentSearch,
    ticketFilteredStudentOptions,
    ticketTargetStudentSet,
    ticketResolvedTargetStudentCount: ticketResolvedTargetStudentIds.size,
    ticketHasExplicitTargets,
    ticketTargetClassCount: ticketTargetClassIds.length,
    ticketTargetStudentCount: ticketTargetStudentIds.length,
    copiedTicketDispatchId,
    onSetSelectedTicketDispatchId: setSelectedTicketDispatchId,
    onSetTicketDispatchImmediateFeedback: setTicketDispatchImmediateFeedback,
    onTicketTargetsFromClassFilter: handleTicketTargetsFromClassFilter,
    onClearTicketTargets: handleClearTicketTargets,
    onToggleTicketTargetClass: handleToggleTicketTargetClass,
    onSetTicketStudentSearch: setTicketStudentSearch,
    onToggleTicketTargetStudent: handleToggleTicketTargetStudent,
    onCopyTicketLink: handleCopyTicketLink,
    onPublishTicketToHome: handlePublishTicketToHome,
    onToggleTicketReveal: handleToggleTicketReveal,
    onClearTicketFromHome: handleClearTicketFromHome,
    onDeleteTicketDispatch: handleDeleteTicketDispatch
  }

  const responsesPanelProps = {
    ticketSelectedDispatch,
    ticketResponseMeta,
    ticketResponseRows,
    onOpenStudentDetail,
    formatTimeAgo,
    ticketHistoryStudentId,
    ticketHistoryStudentOptions,
    ticketHistoryKindFilter,
    ticketHistoryResultFilter,
    ticketHistorySearch,
    ticketHistoryStudent,
    ticketHistorySummary,
    ticketHistoryRows,
    onSetTicketHistoryStudentId: setTicketHistoryStudentId,
    onSetTicketHistoryKindFilter: setTicketHistoryKindFilter,
    onSetTicketHistoryResultFilter: setTicketHistoryResultFilter,
    onSetTicketHistorySearch: setTicketHistorySearch
  }

  return {
    templatePanelProps,
    dispatchPanelProps,
    responsesPanelProps
  }
}
