import { test, expect } from '@playwright/test'
import { createPupil, login, readServerProfile } from './lib/app.js'
import { openTab, teacherLogin } from './lib/teacher.js'
import { readFileSync } from 'node:fs'
const manifest = JSON.parse(readFileSync(new URL('../src/domains/arithmetic/diagnosticTasks.v1.json', import.meta.url), 'utf8'))
test.describe.configure({ mode: 'serial' })

test('A pupil submits each assigned question before continuing without losing saved work', async ({ page, request }, testInfo) => {
  const tag = Math.random().toString(36).slice(2, 8)
  const classId = `ncm-next-${tag}`
  const pupil = await createPupil(request, { name: 'Robot NCM next', classId })
  const teacher = await (await request.post('/__robot/teacher', { data: {
    id: `next-admin-${tag}`, classIds: [classId], role: 'super_admin'
  } })).json()
  await teacherLogin(page, teacher)
  const result = await page.evaluate(async data => {
    const response = await fetch('/api/teacher-diagnostic-assignments', {
      method: 'POST', headers: { 'Content-Type': 'application/json', 'x-teacher-token': sessionStorage.getItem('mathapp_teacher_api_token') }, body: JSON.stringify(data)
    })
    return response.json()
  }, { classId, studentIds: [pupil.studentId], taskIds: manifest.tasks.slice(0, 2).map(task => task.taskId) })
  expect(result.assignment.items).toHaveLength(2)
  await login(page, pupil)
  await page.getByRole('button', { name: manifest.tasks[0].promptSv }).click()
  const firstUrl = page.url()
  await expect(page.getByRole('button', { name: 'Nästa fråga', exact: true })).toBeDisabled()
  await page.locator('input[data-cell="0:0"]').fill('8')
  await page.route('**/api/me/diagnostic-attempt', route => {
    if (route.request().postDataJSON()?.action === 'append') return route.abort('failed')
    return route.continue()
  })
  await page.getByRole('button', { name: 'Lämna in svaret', exact: true }).click()
  await expect(page.getByText(/Arbetet finns kvar i den här fliken/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Nästa fråga', exact: true })).toBeDisabled()
  await page.unroute('**/api/me/diagnostic-attempt')
  await page.getByRole('button', { name: 'Spara arbetet', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Nästa fråga', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('assigned-next-question.png'), fullPage: true })
  await page.getByRole('button', { name: 'Nästa fråga', exact: true }).click()
  await expect(page.getByRole('heading', { name: manifest.tasks[1].promptSv })).toBeVisible()
  await expect(page.locator('input[data-cell="0:0"]')).toBeEnabled()
  await expect(page.locator('input[data-cell="0:0"]')).not.toHaveAttribute('aria-label', /stor siffra 8/)
  await page.getByRole('button', { name: 'Lämna in svaret', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Till min översikt', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Till min översikt', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/student/${pupil.studentId}$`))
  await page.goto(firstUrl)
  await expect(page.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 8/)
  await expect(page.locator('input[data-cell="0:0"]')).toBeDisabled()
})

async function localDiagnosticKeys(page, studentId) {
  return page.evaluate(async id => {
    const open = indexedDB.open(`sequential-math-pilot-vault-${id}`)
    const db = await new Promise((resolve, reject) => {
      open.onsuccess = () => resolve(open.result)
      open.onerror = () => reject(open.error)
    })
    const transaction = db.transaction('records', 'readonly')
    const keys = await new Promise((resolve, reject) => {
      const request = transaction.objectStore('records').getAllKeys()
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    db.close()
    return keys.filter(key => String(key).startsWith('diagnostic:'))
  }, studentId)
}

test('An isolated test pupil can receive, save and resume a diagnostic grid', async ({ page, request, browser }, testInfo) => {
  const tag = Math.random().toString(36).slice(2, 7)
  const classId = `ncm-test-${tag}`
  const className = `NCM test ${tag}`
  const pupil = await createPupil(request, { name: 'Robot NCM', classId, className, operations: ['addition'] })
  const other = await createPupil(request, { name: `Other ${tag}`, classId, className })
  const teacher = await (await request.post('/__robot/teacher', { data: {
    id: `ncm-admin-${tag}`, classIds: [classId], role: 'super_admin'
  } })).json()

  await teacherLogin(page, teacher)
  await openTab(page, 'Screening')
  await expect(page.getByText(/Det sparas separat från vanlig träning/)).toBeVisible()
  const panel = page.getByRole('heading', { name: 'Screening till elev eller klass' }).locator('xpath=..')
  await panel.getByRole('combobox', { name: 'Klass' }).selectOption(classId)
  await expect(panel.getByRole('combobox', { name: 'Elev' }).locator('option')).toHaveCount(2)
  await panel.getByRole('combobox', { name: 'Elev' }).selectOption(pupil.studentId)
  await panel.getByRole('button', { name: 'Ge testuppdrag' }).click()
  await expect(panel.getByText('Testuppdraget är tilldelat.')).toBeVisible()

  const context = await browser.newContext()
  const studentPage = await context.newPage()
  await login(studentPage, pupil)
  const card = studentPage.getByRole('heading', { name: 'Digitalt räknehäfte' }).locator('xpath=..')
  await expect(card.getByRole('button', { name: 'Räkna ut 268 + 431.' })).toBeVisible()
  await card.getByRole('button', { name: 'Räkna ut 268 + 431.' }).click()
  await expect(studentPage.locator('input[data-cell="0:0"]')).toBeVisible()
  await studentPage.screenshot({ path: testInfo.outputPath('diagnostic-pupil.png'), fullPage: true })
  await studentPage.locator('input[data-cell="0:0"]').click()
  await studentPage.keyboard.press('8')
  await expect(studentPage.getByText(/Osparade ändringar/)).toBeVisible()
  await studentPage.getByRole('button', { name: 'Spara arbetet' }).click()
  await expect(studentPage.getByText('Alla skickade ändringar är sparade på servern.')).toBeVisible()
  expect(await localDiagnosticKeys(studentPage, pupil.studentId)).toEqual([])
  await studentPage.reload()
  await expect(studentPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 8/)

  await panel.getByRole('button', { name: 'Uppdatera försök' }).click()
  await expect(panel.getByRole('button', { name: 'Visa underlag' })).toBeVisible()
  await panel.getByRole('button', { name: 'Visa underlag' }).click()
  const evidence = panel.getByRole('region', { name: 'Diagnostiskt elevunderlag' })
  await expect(evidence.getByText(/Sparad elevrevision 1 · 1 händelse/)).toBeVisible()
  await expect(evidence.getByRole('gridcell', { name: /rad 1, kolumn 1, 8/ })).toBeVisible()
  await expect(evidence.getByText(/Kolumnplacering: kan inte avgöras säkert/)).toBeVisible()
  await expect(evidence.getByText(/Synligt resultat och slutsvar: kan inte jämföras säkert/)).toBeVisible()
  await evidence.getByRole('button', { name: 'Början' }).click()
  await expect(evidence.getByRole('gridcell', { name: 'rad 1, kolumn 1, tom' })).toBeVisible()
  await evidence.getByRole('button', { name: 'Slutbild' }).click()
  await expect(evidence.getByRole('gridcell', { name: /rad 1, kolumn 1, 8/ })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('diagnostic-teacher-evidence.png'), fullPage: true })

  const secondContext = await browser.newContext()
  const secondPage = await secondContext.newPage()
  await login(secondPage, pupil)
  await secondPage.getByRole('button', { name: 'Räkna ut 268 + 431.' }).click()
  await expect(secondPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 8/)
  await studentPage.locator('input[data-cell="0:0"]').click()
  await studentPage.keyboard.press('7')
  // This edit is saved by the delayed automatic path, while the other tab
  // still holds an older revision and must keep its conflicting original.
  await expect(studentPage.getByText('Alla skickade ändringar är sparade på servern.')).toBeVisible()
  await secondPage.locator('input[data-cell="0:0"]').click()
  await secondPage.keyboard.press('9')
  await secondPage.getByRole('button', { name: 'Spara arbetet' }).click()
  await expect(secondPage.getByText(/Arbetet finns kvar i den här fliken/)).toBeVisible()
  await expect(secondPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 9/)
  secondPage.once('dialog', dialog => dialog.accept())
  await secondPage.reload()
  await expect(secondPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 9/)
  await expect(secondPage.getByText(/Arbetet skiljer sig från serverns version/)).toBeVisible()
  await expect(secondPage.getByRole('button', { name: 'Spara arbetet' })).toBeDisabled()
  expect(await localDiagnosticKeys(secondPage, pupil.studentId)).toHaveLength(1)
  await studentPage.reload()
  await expect(studentPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 7/)
  await studentPage.route('**/api/me/diagnostic-attempt', route => {
    if (route.request().postDataJSON()?.action === 'append') return route.abort('failed')
    return route.continue()
  })
  await studentPage.locator('input[data-cell="0:0"]').click()
  await studentPage.keyboard.press('6')
  await expect(studentPage.getByText('Sparat krypterat på den här enheten. Väntar på serverkvittens.')).toBeVisible()
  expect(await localDiagnosticKeys(studentPage, pupil.studentId)).toHaveLength(1)
  studentPage.once('dialog', dialog => dialog.accept())
  await studentPage.reload()
  await expect(studentPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 6/)
  await studentPage.unroute('**/api/me/diagnostic-attempt')
  await studentPage.getByRole('button', { name: 'Spara arbetet' }).click()
  await expect(studentPage.getByText('Alla skickade ändringar är sparade på servern.')).toBeVisible()
  expect(await localDiagnosticKeys(studentPage, pupil.studentId)).toEqual([])
  await studentPage.reload()
  await expect(studentPage.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 6/)
  const profile = await readServerProfile(request, pupil.studentId)
  expect(profile.problemLog).toEqual([])
  expect(profile.recentProblems).toEqual([])

  const otherContext = await browser.newContext()
  const otherPage = await otherContext.newPage()
  await login(otherPage, other)
  await expect(otherPage.getByRole('heading', { name: 'Digitalt räknehäfte' })).toHaveCount(0)
  await studentPage.locator('input[data-cell="0:0"]').click()
  await studentPage.keyboard.type('89'.repeat(600))
  await expect(studentPage.getByRole('alert').getByText('Räknehäftet är fullt.', { exact: false })).toBeVisible()
  await expect(studentPage.getByText(/Händelser: 1024\./)).toBeVisible()
  await studentPage.keyboard.press('7')
  await expect(studentPage.getByText(/Händelser: 1024\./)).toBeVisible()
  await otherContext.close()
  await secondContext.close()
  await context.close()
})
