import { test, expect } from '@playwright/test'
import { createPupil, login, readServerProfile } from './lib/app.js'
import { teacherLogin, openTab } from './lib/teacher.js'

test('R2/R3: Svara saves without freezing; navigation preserves work and submission covers the collection', async ({ page, request }) => {
  const tag = Math.random().toString(36).slice(2, 8)
  const classId = `collection-${tag}`
  const pupil = await createPupil(request, { name: 'Collections A', classId })
  const teacher = await (await request.post('/__robot/teacher', { data: {
    id: `collection-admin-${tag}`, classIds: [classId], role: 'super_admin'
  } })).json()
  await teacherLogin(page, teacher)
  await page.evaluate(async data => {
    const response = await fetch('/api/teacher-diagnostic-assignments', {
      method: 'POST', headers: { 'Content-Type': 'application/json',
        'x-teacher-token': sessionStorage.getItem('mathapp_teacher_api_token') }, body: JSON.stringify(data)
    })
    if (!response.ok) throw new Error('Could not assign collection')
  }, { classId, studentIds: [pupil.studentId], titleSv: 'Screening – växling',
    taskIds: ['add-carry-001', 'sub-through-zero-001'] })
  await login(page, pupil)
  await page.getByRole('button', { name: 'Screening – växling', exact: true }).click()
  await page.locator('input[data-cell="0:0"]').click()
  await page.getByRole('button', { name: 'Skriv 8', exact: true }).click()
  await expect(page.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 8/)
  await page.locator('#diagnostic-answer').click()
  await page.getByRole('button', { name: 'Skriv 5', exact: true }).click()
  await page.getByRole('button', { name: 'Svara', exact: true }).click()
  await expect(page.getByText('Alla skickade ändringar är sparade på servern.')).toBeVisible()
  await expect(page.locator('input[data-cell="0:0"]')).toBeEnabled()
  await page.getByRole('button', { name: 'Nästa fråga', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Räkna ut 402 − 178.' })).toBeVisible()
  await page.getByRole('button', { name: 'Förra frågan', exact: true }).click()
  await expect(page.locator('#diagnostic-answer')).toHaveValue('5')
  await expect(page.locator('input[data-cell="0:0"]')).toHaveAttribute('aria-label', /stor siffra 8/)
  await page.locator('#diagnostic-answer').press('Delete')
  await page.locator('#diagnostic-answer').pressSequentially('575')
  await page.getByRole('button', { name: 'Nästa fråga', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Nästa fråga', exact: true })).toHaveCount(0)
  const submit = page.getByRole('button', { name: 'Lämna in svaren', exact: true })
  let warning = ''
  page.once('dialog', async dialog => { warning = dialog.message(); await dialog.dismiss() })
  await submit.click()
  await expect.poll(() => warning).toMatch(/obesvarad|saknar svar/i)
  await expect(page.locator('input[data-cell="0:0"]')).toBeEnabled()
  await page.locator('#diagnostic-answer').click()
  await page.locator('#diagnostic-answer').pressSequentially('224')
  await page.route('**/api/me/diagnostic-attempt', route => route.request().postDataJSON()?.action === 'submit_collection'
    ? route.abort('failed') : route.continue())
  await submit.click()
  await expect(page.getByRole('alert')).toContainText(/inte|Kunde/)
  await expect(page.locator('input[data-cell="0:0"]')).toBeEnabled()
  await page.unroute('**/api/me/diagnostic-attempt')
  await submit.click()
  await expect(page.getByText('Samlingen är inlämnad.')).toBeVisible()
  await page.getByRole('button', { name: '← Till min översikt', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Screening – växling', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Inlämnade samlingar', exact: true }).selectOption({ label: 'Screening – växling · Inlämnad' })
  await expect(page.locator('#diagnostic-answer')).toHaveValue('575')
  await expect(page.locator('#diagnostic-answer')).toBeDisabled()
  const profile = await readServerProfile(request, pupil.studentId)
  expect(profile.problemLog).toEqual([])
})

test('Teacher assigns a written answer with saved drawing; eraser and explicit feedback preserve the pupil original', async ({ page, request, browser }, testInfo) => {
  const tag = Math.random().toString(36).slice(2, 8)
  const classId = `writing-${tag}`
  const pupil = await createPupil(request, { name: 'Collections B', classId })
  const teacher = await (await request.post('/__robot/teacher', { data: {
    id: `writing-admin-${tag}`, classIds: [classId], role: 'super_admin'
  } })).json()
  await teacherLogin(page, teacher)
  await openTab(page, 'Screening')
  const panel = page.getByRole('heading', { name: 'Screening till elev eller klass' }).locator('xpath=..')
  await panel.getByRole('combobox', { name: 'Klass', exact: true }).selectOption(classId)
  await panel.getByRole('combobox', { name: 'Elev', exact: true }).selectOption(pupil.studentId)
  await panel.getByRole('textbox', { name: 'Samlingens namn', exact: true }).fill('Skriv – förklara')
  const choices = panel.locator('fieldset').first().getByRole('checkbox')
  for (const choice of await choices.all()) await choice.uncheck()
  await panel.getByText('Lägg till egen skrivfråga', { exact: true }).click()
  await panel.getByRole('textbox', { name: 'Frågetext', exact: true }).fill('Förklara hur du växlar en tia.')
  await panel.getByRole('checkbox', { name: 'Räknehäfte till skrivfrågan', exact: true }).check()
  await panel.getByRole('checkbox', { name: 'Rityta till skrivfrågan', exact: true }).check()
  await panel.getByRole('button', { name: 'Ge testuppdrag', exact: true }).click()
  await expect(panel.getByText('Testuppdraget är tilldelat.')).toBeVisible()
  const context = await browser.newContext({ viewport: { width: 820, height: 1180 }, hasTouch: true })
  const student = await context.newPage()
  await login(student, pupil)
  await student.getByRole('button', { name: 'Skriv – förklara', exact: true }).click()
  await student.locator('input[data-cell="0:0"]').click()
  await student.getByRole('button', { name: 'Skriv 8', exact: true }).click()
  await student.getByRole('button', { name: 'Suddverktyg', exact: true }).click()
  await student.locator('input[data-cell="0:0"]').tap()
  await expect(student.locator('input[data-cell="0:0"]')).not.toHaveAttribute('aria-label', /stor siffra 8/)
  await student.getByRole('button', { name: 'Suddverktyg', exact: true }).click()
  await student.locator('#diagnostic-answer').fill('En tia blir tio ental.')
  const canvas = student.locator('canvas')
  const blank = await canvas.evaluate(element => element.toDataURL())
  const box = await canvas.boundingBox()
  await student.mouse.move(box.x + 40, box.y + 40)
  await student.mouse.down()
  await student.mouse.move(box.x + 100, box.y + 80, { steps: 6 })
  await student.mouse.up()
  await expect.poll(() => canvas.evaluate(element => element.toDataURL())).not.toBe(blank)
  const drawn = await canvas.evaluate(element => element.toDataURL())
  await student.getByRole('button', { name: 'Svara', exact: true }).click()
  await expect(student.getByText('Alla skickade ändringar är sparade på servern.')).toBeVisible()
  await student.reload()
  await expect(student.locator('#diagnostic-answer')).toHaveValue('En tia blir tio ental.')
  await expect.poll(() => canvas.evaluate(element => element.toDataURL())).toBe(drawn)
  await student.screenshot({ path: testInfo.outputPath('written-drawing-ipad.png'), fullPage: true })
  await student.getByRole('button', { name: 'Lämna in svaren', exact: true }).click()
  await expect(student.getByText('Samlingen är inlämnad.')).toBeVisible()
  await panel.getByRole('button', { name: 'Uppdatera försök', exact: true }).click()
  await panel.getByRole('button', { name: 'Visa underlag', exact: true }).click()
  await expect(panel.getByText(/^Slutsvar: En tia blir tio ental/)).toBeVisible()
  await panel.getByRole('button', { name: 'Grupp', exact: true }).click()
  const review = panel.getByRole('region', { name: 'Klassgenomgång', exact: true })
  await review.getByRole('combobox', { name: 'Uppdrag att gå igenom', exact: true }).selectOption({ index: 1 })
  await review.getByRole('button', { name: /Förklara hur du växlar/ }).click()
  const form = review.getByRole('form', { name: 'Lärarens genomgång', exact: true })
  await form.getByRole('textbox', { name: 'Läraranteckning', exact: true }).fill('PRIVATE INTERNAL NOTE')
  await form.getByRole('textbox', { name: 'Återkoppling till eleven', exact: true }).fill('Bra förklaring. Visa även i rutorna.')
  await form.getByRole('button', { name: 'Skicka återkoppling', exact: true }).click()
  await expect(form.getByText('Återkopplingen är skickad till eleven.')).toBeVisible()
  await student.getByRole('button', { name: '← Till min översikt', exact: true }).click()
  await student.getByRole('combobox', { name: 'Inlämnade samlingar', exact: true })
    .selectOption({ label: 'Skriv – förklara · Återkoppling finns' })
  await expect(student.getByRole('region', { name: 'Återkoppling från läraren' })).toContainText('Bra förklaring.')
  await expect(student.getByText('PRIVATE INTERNAL NOTE')).toHaveCount(0)
  await expect(student.locator('#diagnostic-answer')).toBeDisabled()
  await expect.poll(() => canvas.evaluate(element => element.toDataURL())).toBe(drawn)
  await context.close()
})
