import { test, expect } from '@playwright/test'
import { createPupil, login, openOtherTraining, waitForTask } from './lib/app.js'

test('Rityta: färg, rutnät, sudd och bekräftad rensning bevarar elevens val', async ({ page, request }, testInfo) => {
  await login(page, await createPupil(request))
  await openOtherTraining(page)
  await page.getByRole('button', { name: /^Addition/ }).click()
  await waitForTask(page)
  await page.getByRole('button', { name: 'Visa rityta', exact: true }).click()
  const canvas = page.getByLabel('Rityta', { exact: true })
  const tools = page.getByRole('group', { name: 'Ritverktyg' })
  const pixel = () => canvas.evaluate(c => [...c.getContext('2d').getImageData(40, 40, 1, 1).data])
  const dot = async () => {
    const box = await canvas.boundingBox()
    const size = await canvas.evaluate(c => ({ width: c.width, height: c.height }))
    await page.mouse.click(box.x + 40 * box.width / size.width, box.y + 40 * box.height / size.height)
  }
  await tools.getByRole('button', { name: 'Penna, svart' }).click()
  await expect(tools.getByRole('button', { name: 'Penna, magenta' })).toHaveAttribute('aria-pressed', 'true')
  await dot()
  const ink = await pixel()
  expect(ink[0]).toBeGreaterThan(100)
  expect(ink[1]).toBeLessThan(30)
  expect(ink[3]).toBeGreaterThan(0)
  await tools.getByRole('button', { name: 'Kvadratiskt rutmönster' }).click()
  expect(await pixel()).toEqual(ink)
  await expect(canvas).toHaveCSS('background-size', /^24px 24px/)
  await tools.getByRole('button', { name: 'Penna, magenta' }).click()
  await expect(tools.getByRole('button', { name: 'Penna, svart' })).toBeVisible()
  await tools.getByRole('button', { name: 'Sudd', exact: true }).click()
  await dot()
  expect((await pixel())[3]).toBe(0)
  await tools.getByRole('button', { name: 'Penna, svart' }).click()
  await dot()
  const black = await pixel()
  expect(black[3]).toBeGreaterThan(0)
  await expect(tools.getByRole('button', { name: 'Penna, svart' })).toHaveCSS('background-color', 'oklch(0.208 0.042 265.755)')
  const picker = page.getByLabel('Välj tema')
  const themes = await picker.locator('option').evaluateAll(options => options.map(option => option.value))
  for (const theme of themes) {
    await picker.selectOption(theme)
    await expect(canvas).toHaveCSS('background-color', 'rgb(255, 255, 255)')
    await expect(tools.getByRole('button', { name: 'Penna, svart' })).toHaveCSS('background-color', 'oklch(0.208 0.042 265.755)')
    await expect(tools.getByRole('button', { name: 'Penna, svart' })).toHaveCSS('color', 'rgb(255, 255, 255)')
  }
  await page.screenshot({ path: testInfo.outputPath('scratchpad-tools.png'), fullPage: true })
  await page.getByRole('button', { name: 'Dölj rityta' }).click()
  await page.getByRole('button', { name: 'Visa rityta', exact: true }).click()
  expect(await pixel()).toEqual(black)
  page.once('dialog', dialog => dialog.dismiss())
  await tools.getByRole('button', { name: 'Rensa ritytan' }).click()
  expect(await pixel()).toEqual(black)
  page.once('dialog', dialog => dialog.accept())
  await tools.getByRole('button', { name: 'Rensa ritytan' }).click()
  expect((await pixel())[3]).toBe(0)
  await expect(canvas).toHaveCSS('background-size', /^24px 24px/)
})
